DROP TABLE items, users;

CREATE TABLE items (
    _id UNIQUEIDENTIFIER NOT NULL UNIQUE PRIMARY KEY DEFAULT NEWID(),
    user_id: UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES users(_id), 
    title: VARCHAR(255) NOT NULL DEFAULT 'Untitled',
    created_time: DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_time: DATETIME DEFAULT CURRENT_TIMESTAMP,
    content: VARCHAR(max),
);

CREATE TABLE users (
    _id UNIQUEIDENTIFIER NOT NULL UNIQUE PRIMARY KEY DEFAULT NEWID(),
    name: VARCHAR(255) NOT NULL,
    password: VARCHAR(255) NOT NULL,
    created_time: DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_time: DATETIME DEFAULT CURRENT_TIMESTAMP,
);
